name: 🐛 Bug Report
description: Report a bug or issue with Open WebUI Hub
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - DIZ-admin

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Open WebUI
        - Docling Service
        - Tika Service
        - Ollama
        - LiteLLM
        - SearXNG
        - PostgreSQL
        - Redis
        - Hub Service
        - Docker Compose
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
        - Docker version: [e.g. 24.0.0]
        - Docker Compose version: [e.g. 2.20.0]
        - Browser: [e.g. Chrome 118, Firefox 119]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide relevant logs
      placeholder: |
        Paste relevant logs here. You can get logs using:
        docker-compose -f compose.local.yml logs [service_name]
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version
          required: false
